# azure-pipelines.yml - Sample CI/CD Pipeline for Deploying the App to Azure App Service
#
# This pipeline is triggered on pushes to the 'master' branch.
# It installs Python, runs tests, and deploys the app to the specified Azure Web App.
#
trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.11'
      addToPath: true

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install Dependencies'

  - script: |
      python -m unittest discover tests
    displayName: 'Run Tests'

  - task: AzureWebApp@1
    inputs:
      azureSubscription: '<your-azure-subscription-connection>'
      appName: '<your-app-service-name>'
      package: '$(System.DefaultWorkingDirectory)'
    displayName: 'Deploy to Azure App Service'
